import { initializeApp, getApps } from 'https://www.gstatic.com/firebasejs/10.8.0/firebase-app.js';
import { getAuth } from 'https://www.gstatic.com/firebasejs/10.8.0/firebase-auth.js';
import { getFirestore, doc, getDoc, setDoc, serverTimestamp } from 'https://www.gstatic.com/firebasejs/10.8.0/firebase-firestore.js';
const config={apiKey:'AIzaSyBqZSb3ZkI1QqoLGyP47ckD7eexwdStdXk',authDomain:'app-futbol-acd0f.firebaseapp.com',projectId:'app-futbol-acd0f',storageBucket:'app-futbol-acd0f.firebasestorage.app',messagingSenderId:'223446110165',appId:'1:223446110165:web:219afce6a9dac03203f75c'};
const app=getApps().length?getApps()[0]:initializeApp(config),auth=getAuth(app),db=getFirestore(app);
const $=id=>document.getElementById(id);
function inject(){const weekly=document.querySelector('.weekly-config');if(!weekly||document.getElementById('general-hours'))return;const el=document.createElement('div');el.id='general-hours';el.className='general-hours';el.innerHTML='<div class="general-hours-head"><div><span class="mini-label">HORARIO GENERAL</span><h3>Hora de inicio y hora de cierre</h3><p>Este horario será el predeterminado para tu negocio. Luego puedes personalizar cada día.</p></div></div><div class="form-two"><label>Hora de inicio<input type="time" id="admin-hora-inicio" value="16:00"></label><label>Hora de cierre<input type="time" id="admin-hora-cierre" value="23:00"></label></div>';weekly.insertBefore(el,weekly.querySelector('.weekly-hours'));}
async function load(){inject();const u=auth.currentUser;if(!u)return;const s=await getDoc(doc(db,'canchas',u.uid));if(!s.exists())return;const d=s.data();if($('admin-hora-inicio'))$('admin-hora-inicio').value=d.horaApertura||'16:00';if($('admin-hora-cierre'))$('admin-hora-cierre').value=d.horaCierre||'23:00';}
function save(e){const form=$('form-perfil-cancha');if(!form||!$('admin-hora-inicio'))return;const original=e.target;/* This listener only augments the normal dashboard save; it writes the general defaults after validation. */setTimeout(async()=>{try{const u=auth.currentUser;if(!u)return;const inicio=$('admin-hora-inicio').value,cierre=$('admin-hora-cierre').value;if(!inicio||!cierre)return;const [ih,im]=inicio.split(':').map(Number),[ch,cm]=cierre.split(':').map(Number);if(ch*60+cm<=ih*60+im){alert('La hora de cierre debe ser posterior a la hora de inicio.');return}await setDoc(doc(db,'canchas',u.uid),{horaApertura:inicio,horaCierre:cierre,updatedAt:serverTimestamp()},{merge:true});}catch(err){console.error('Horario general:',err)}},50)}
const boot=()=>{inject();load();const f=$('form-perfil-cancha');if(f&&!f.dataset.hoursBound){f.dataset.hoursBound='1';f.addEventListener('submit',save,false)}};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();