import { initializeApp } from "https://www.gstatic.com/firebasejs/10.8.0/firebase-app.js";
import { getFirestore, collection, getDocs } from "https://www.gstatic.com/firebasejs/10.8.0/firebase-firestore.js";

const firebaseConfig={apiKey:"AIzaSyBqZSb3ZkI1QqoLGyP47ckD7eexwdStdXk",authDomain:"app-futbol-acd0f.firebaseapp.com",projectId:"app-futbol-acd0f",storageBucket:"app-futbol-acd0f.firebasestorage.app",messagingSenderId:"223446110165",appId:"1:223446110165:web:219afce6a9dac03203f75c"};
const app=initializeApp(firebaseConfig),db=getFirestore(app);
const mapEl=document.getElementById('map-canchas');

if(mapEl&&window.L){
  const map=L.map(mapEl,{zoomControl:false,scrollWheelZoom:true,fadeAnimation:true}).setView([-5.1945,-80.6328],13);
  L.control.zoom({position:'bottomright'}).addTo(map);
  const carto=L.tileLayer('https://{s}.basemaps.cartocdn.com/rastertiles/voyager/{z}/{x}/{y}{r}.png',{subdomains:'abcd',maxZoom:20,attribution:'&copy; OpenStreetMap contributors &copy; CARTO'});
  const osm=L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap contributors'});
  let fallback=false;carto.on('tileerror',()=>{if(!fallback){fallback=true;map.removeLayer(carto);osm.addTo(map)}});carto.addTo(map);
  const markers=L.layerGroup().addTo(map),userLayer=L.layerGroup().addTo(map),status=document.getElementById('map-status'),btn=document.getElementById('btn-mi-ubicacion');
  const icon=L.divIcon({className:'premium-map-marker',html:'<div><i class="ph-fill ph-soccer-ball"></i></div>',iconSize:[40,40],iconAnchor:[20,38],popupAnchor:[0,-38]});
  const userIcon=L.divIcon({className:'user-map-marker',html:'<div><span></span></div>',iconSize:[24,24],iconAnchor:[12,12]});
  const escapeHtml=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
  function coords(c){let lat=Number(c.lat),lng=Number(c.lng);if(Number.isFinite(lat)&&Number.isFinite(lng))return[lat,lng];const u=String(c.ubicacionLink||'');let m=u.match(/@(-?\d+(?:\.\d+)?),(-?\d+(?:\.\d+)?)/);if(!m)m=u.match(/[?&](?:q|ll)=(-?\d+(?:\.\d+)?)[,%20]+(-?\d+(?:\.\d+)?)/);return m?[Number(m[1]),Number(m[2])]:null}
  function isOpen(c){if(!c.horaApertura||!c.horaCierre)return false;const n=new Date(),now=n.getHours()*60+n.getMinutes(),[ha,ma]=c.horaApertura.split(':').map(Number),[hc,mc]=c.horaCierre.split(':').map(Number),a=ha*60+ma,b=hc*60+mc;return b>a?now>=a&&now<=b:now>=a||now<=b}
  function popup(c){const open=isOpen(c),rating=Number(c.ratingPromedio||c.rating||0),foto=c.fotos?.[0]||'https://images.unsplash.com/photo-1518605368461-1e1e38ce81ba?auto=format&fit=crop&w=500&q=80';return `<div class="map-popup premium-popup"><div class="map-popup-cover" style="background-image:url('${escapeHtml(foto)}')"><span class="map-popup-status ${open?'open':'closed'}"><i class="ph-fill ph-circle"></i> ${open?'Abierto ahora':'Cerrado'}</span></div><div class="map-popup-body"><strong>${escapeHtml(c.nombre||'Cancha')}</strong><span class="map-popup-rating"><i class="ph-fill ph-star"></i> ${rating?rating.toFixed(1):'Nuevo'} · ${escapeHtml(c.tipoCancha||c.tipo||'Fútbol')}</span><span><i class="ph-bold ph-map-pin"></i> ${escapeHtml(c.ubicacionTexto||c.ciudad||'Ubicación disponible')}</span><div class="map-popup-price">${c.precio!=null?`S/ ${escapeHtml(c.precio)} <small>/ hora</small>`:'Consultar precio'}</div><div class="map-popup-actions"><button type="button" class="map-open-card" data-id="${escapeHtml(c.id)}">Ver cancha</button>${c.ubicacionLink?`<a href="${escapeHtml(c.ubicacionLink)}" target="_blank" rel="noopener">Ruta <i class="ph-bold ph-arrow-up-right"></i></a>`:''}</div></div></div>`}
  async function cargar(){try{const snap=await getDocs(collection(db,'canchas')),bounds=[];snap.forEach(ds=>{const c={id:ds.id,...ds.data()};if(c.configurado===false)return;const pos=coords(c);if(!pos)return;const marker=L.marker(pos,{icon}).bindPopup(popup(c),{maxWidth:290,minWidth:240});marker.on('popupopen',()=>{const el=document.querySelector(`.map-open-card[data-id="${CSS.escape(c.id)}"]`);el?.addEventListener('click',()=>window.abrirModal?.(c.id))});marker.addTo(markers);bounds.push(pos)});if(bounds.length){map.fitBounds(bounds,{padding:[45,45],maxZoom:14});status.textContent=`${bounds.length} cancha${bounds.length===1?'':'s'} ubicada${bounds.length===1?'':'s'} en el mapa.`}else status.textContent='No hay canchas con coordenadas todavía. Los dueños pueden añadir su ubicación desde su panel.';setTimeout(()=>map.invalidateSize(true),100);setTimeout(()=>map.invalidateSize(true),700)}catch(e){console.error('APP FUTBOL mapa:',e);status.textContent='No pudimos cargar las ubicaciones. Puedes seguir usando los filtros.';setTimeout(()=>map.invalidateSize(true),200)}}
  function ubicarUsuario(){if(!navigator.geolocation){status.textContent='Tu navegador no admite geolocalización.';return}btn?.setAttribute('disabled','disabled');status.textContent='Obteniendo tu ubicación…';navigator.geolocation.getCurrentPosition(pos=>{const lat=pos.coords.latitude,lng=pos.coords.longitude;userLayer.clearLayers();L.marker([lat,lng],{icon:userIcon}).addTo(userLayer).bindPopup('<strong>Estás aquí</strong>').openPopup();L.circle([lat,lng],{radius:1000,color:'#00D968',fillColor:'#00D968',fillOpacity:.08,weight:1}).addTo(userLayer);map.setView([lat,lng],14);status.textContent='Ubicación activada. Explora las canchas cercanas.';btn?.removeAttribute('disabled')},()=>{status.textContent='No pudimos acceder a tu ubicación. Revisa el permiso del navegador.';btn?.removeAttribute('disabled')},{enableHighAccuracy:true,timeout:10000,maximumAge:30000})}
  btn?.addEventListener('click',ubicarUsuario);cargar();window.addEventListener('resize',()=>map.invalidateSize(true));
}
